data_path: ./data/Project33.csv
end_date: '2024-09-28'
epochs: 1
forecast_features:
- global_tilted_irradiance_pred
- vapour_pressure_deficit_pred
- relative_humidity_2m_pred
- temperature_2m_pred
- wind_gusts_10m_pred
- cloud_cover_low_pred
- wind_speed_100m_pred
- snow_depth_pred
- dew_point_2m_pred
- precipitation_pred
- surface_pressure_pred
future_hours: 24
model: LSR
model_complexity: baseline
past_days: 3
past_hours: 72
plot_days: 7
save_dir: ./temp_results/Project33
save_options:
  save_excel_results: false
  save_model: false
  save_predictions: false
  save_summary: false
  save_training_log: false
start_date: '2022-01-01'
train_params: {}
train_ratio: 0.8
use_forecast: true
use_hist_weather: false
use_pv: false
use_time_encoding: false
val_ratio: 0.1
weather_features: []
